skimlinks.settings:
  type: config_object
  label: 'Skimlinks settings'
  mapping:
    domainid:
      type: string
      label: 'Domain ID'
    subdomain:
      type: string
      label: 'Custom redirection sub domain'